{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4844e777",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing https://insights.blackcoffer.com/rising-it-cities-will-impact-the-economy-environment-infrastructure-and-city-life-by-the-year-2035/: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))\n",
      "Error processing https://insights.blackcoffer.com/rise-of-ott-platform-and-its-impact-on-entertainment-industry-by-the-year-2030/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /rise-of-ott-platform-and-its-impact-on-entertainment-industry-by-the-year-2030/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/rise-of-electric-vehicles-and-its-impact-on-livelihood-by-2040/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /rise-of-electric-vehicles-and-its-impact-on-livelihood-by-2040/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CACA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/rise-of-electric-vehicle-and-its-impact-on-livelihood-by-the-year-2040/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /rise-of-electric-vehicle-and-its-impact-on-livelihood-by-the-year-2040/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/oil-prices-by-the-year-2040-and-how-it-will-impact-the-world-economy/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /oil-prices-by-the-year-2040-and-how-it-will-impact-the-world-economy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/an-outlook-of-healthcare-by-the-year-2040-and-how-it-will-impact-human-lives/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /an-outlook-of-healthcare-by-the-year-2040-and-how-it-will-impact-human-lives/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/ai-in-healthcare-to-improve-patient-outcomes/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /ai-in-healthcare-to-improve-patient-outcomes/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-if-the-creation-is-taking-over-the-creator/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-if-the-creation-is-taking-over-the-creator/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-jobs-will-robots-take-from-humans-in-the-future/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-jobs-will-robots-take-from-humans-in-the-future/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/will-machine-replace-the-human-in-the-future-of-work/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /will-machine-replace-the-human-in-the-future-of-work/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/will-ai-replace-us-or-work-with-us/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /will-ai-replace-us-or-work-with-us/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/man-and-machines-together-machines-are-more-diligent-than-humans-blackcoffe/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /man-and-machines-together-machines-are-more-diligent-than-humans-blackcoffe/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/in-future-or-in-upcoming-years-humans-and-machines-are-going-to-work-together-in-every-field-of-work/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /in-future-or-in-upcoming-years-humans-and-machines-are-going-to-work-together-in-every-field-of-work/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-neural-networks-can-be-applied-in-various-areas-in-the-future/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-neural-networks-can-be-applied-in-various-areas-in-the-future/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-machine-learning-will-affect-your-business/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-machine-learning-will-affect-your-business/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/deep-learning-impact-on-areas-of-e-learning/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /deep-learning-impact-on-areas-of-e-learning/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-to-protect-future-data-and-its-privacy-blackcoffer/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-to-protect-future-data-and-its-privacy-blackcoffer/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-machines-ai-automations-and-robo-human-are-effective-in-finance-and-banking/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-machines-ai-automations-and-robo-human-are-effective-in-finance-and-banking/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/ai-human-robotics-machine-future-planet-blackcoffer-thinking-jobs-workplace/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /ai-human-robotics-machine-future-planet-blackcoffer-thinking-jobs-workplace/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-ai-will-change-the-world-blackcoffer/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-ai-will-change-the-world-blackcoffer/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/future-of-work-how-ai-has-entered-the-workplace/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /future-of-work-how-ai-has-entered-the-workplace/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/ai-tool-alexa-google-assistant-finance-banking-tool-future/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /ai-tool-alexa-google-assistant-finance-banking-tool-future/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/ai-healthcare-revolution-ml-technology-algorithm-google-analytics-industrialrevolution/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /ai-healthcare-revolution-ml-technology-algorithm-google-analytics-industrialrevolution/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/all-you-need-to-know-about-online-marketing/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /all-you-need-to-know-about-online-marketing/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/evolution-of-advertising-industry/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /evolution-of-advertising-industry/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-data-analytics-can-help-your-business-respond-to-the-impact-of-covid-19/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-data-analytics-can-help-your-business-respond-to-the-impact-of-covid-19/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/covid-19-environmental-impact-for-the-future/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /covid-19-environmental-impact-for-the-future/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/environmental-impact-of-the-covid-19-pandemic-lesson-for-the-future/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /environmental-impact-of-the-covid-19-pandemic-lesson-for-the-future/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-data-analytics-and-ai-are-used-to-halt-the-covid-19-pandemic/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-data-analytics-and-ai-are-used-to-halt-the-covid-19-pandemic/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/difference-between-artificial-intelligence-machine-learning-statistics-and-data-mining/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /difference-between-artificial-intelligence-machine-learning-statistics-and-data-mining/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-python-became-the-first-choice-for-data-science/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-python-became-the-first-choice-for-data-science/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-google-fit-measure-heart-and-respiratory-rates-using-a-phone/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-google-fit-measure-heart-and-respiratory-rates-using-a-phone/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-is-the-future-of-mobile-apps/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-is-the-future-of-mobile-apps/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impact-of-ai-in-health-and-medicine/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impact-of-ai-in-health-and-medicine/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/telemedicine-what-patients-like-and-dislike-about-it/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /telemedicine-what-patients-like-and-dislike-about-it/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-we-forecast-future-technologies/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-we-forecast-future-technologies/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/can-robots-tackle-late-life-loneliness/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /can-robots-tackle-late-life-loneliness/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/embedding-care-robots-into-society-socio-technical-considerations/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /embedding-care-robots-into-society-socio-technical-considerations/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/management-challenges-for-future-digitalization-of-healthcare-services/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /management-challenges-for-future-digitalization-of-healthcare-services/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/are-we-any-closer-to-preventing-a-nuclear-holocaust/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /are-we-any-closer-to-preventing-a-nuclear-holocaust/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/will-technology-eliminate-the-need-for-animal-testing-in-drug-development/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /will-technology-eliminate-the-need-for-animal-testing-in-drug-development/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/will-we-ever-understand-the-nature-of-consciousness/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /will-we-ever-understand-the-nature-of-consciousness/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/will-we-ever-colonize-outer-space/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /will-we-ever-colonize-outer-space/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-is-the-chance-homo-sapiens-will-survive-for-the-next-500-years/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-is-the-chance-homo-sapiens-will-survive-for-the-next-500-years/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing https://insights.blackcoffer.com/why-does-your-business-need-a-chatbot/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /why-does-your-business-need-a-chatbot/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-you-lead-a-project-or-a-team-without-any-technical-expertise/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-you-lead-a-project-or-a-team-without-any-technical-expertise/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/can-you-be-great-leader-without-technical-expertise/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /can-you-be-great-leader-without-technical-expertise/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-does-artificial-intelligence-affect-the-environment/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-does-artificial-intelligence-affect-the-environment/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-to-overcome-your-fear-of-making-mistakes-2/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-to-overcome-your-fear-of-making-mistakes-2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/is-perfection-the-greatest-enemy-of-productivity/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /is-perfection-the-greatest-enemy-of-productivity/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/global-financial-crisis-2008-causes-effects-and-its-solution/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /global-financial-crisis-2008-causes-effects-and-its-solution/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/gender-diversity-and-equality-in-the-tech-industry/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /gender-diversity-and-equality-in-the-tech-industry/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CACA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-to-overcome-your-fear-of-making-mistakes/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-to-overcome-your-fear-of-making-mistakes/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-small-business-can-survive-the-coronavirus-crisis/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-small-business-can-survive-the-coronavirus-crisis/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impacts-of-covid-19-on-vegetable-vendors-and-food-stalls/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impacts-of-covid-19-on-vegetable-vendors-and-food-stalls/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impacts-of-covid-19-on-vegetable-vendors/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impacts-of-covid-19-on-vegetable-vendors/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-tourism-aviation-industries/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impact-of-covid-19-pandemic-on-tourism-aviation-industries/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-sports-events-around-the-world/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impact-of-covid-19-pandemic-on-sports-events-around-the-world/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/changing-landscape-and-emerging-trends-in-the-indian-it-ites-industry/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /changing-landscape-and-emerging-trends-in-the-indian-it-ites-industry/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/online-gaming-adolescent-online-gaming-effects-demotivated-depression-musculoskeletal-and-psychosomatic-symptoms/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /online-gaming-adolescent-online-gaming-effects-demotivated-depression-musculoskeletal-and-psychosomatic-symptoms/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/human-rights-outlook/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /human-rights-outlook/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-voice-search-makes-your-business-a-successful-business/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-voice-search-makes-your-business-a-successful-business/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-the-covid-19-crisis-is-redefining-jobs-and-services/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-the-covid-19-crisis-is-redefining-jobs-and-services/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CABE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-to-increase-social-media-engagement-for-marketers/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-to-increase-social-media-engagement-for-marketers/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impacts-of-covid-19-on-streets-sides-food-stalls/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impacts-of-covid-19-on-streets-sides-food-stalls/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/coronavirus-impact-on-energy-markets-2/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /coronavirus-impact-on-energy-markets-2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry-5/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /coronavirus-impact-on-the-hospitality-industry-5/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis-4/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis-4/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA9A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/estimating-the-impact-of-covid-19-on-the-world-of-work-2/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /estimating-the-impact-of-covid-19-on-the-world-of-work-2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/estimating-the-impact-of-covid-19-on-the-world-of-work-3/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /estimating-the-impact-of-covid-19-on-the-world-of-work-3/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/travel-and-tourism-outlook/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /travel-and-tourism-outlook/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CACA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/gaming-disorder-and-effects-of-gaming-on-health/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /gaming-disorder-and-effects-of-gaming-on-health/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation-2/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation-2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-office-space-and-co-working-industries/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /impact-of-covid-19-pandemic-on-office-space-and-co-working-industries/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAA30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/contribution-of-handicrafts-visual-arts-literature-in-the-indian-economy/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /contribution-of-handicrafts-visual-arts-literature-in-the-indian-economy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-covid-19-is-impacting-payment-preferences/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-covid-19-is-impacting-payment-preferences/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CAAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error processing https://insights.blackcoffer.com/how-will-covid-19-affect-the-world-of-work-2/: HTTPSConnectionPool(host='insights.blackcoffer.com', port=443): Max retries exceeded with url: /how-will-covid-19-affect-the-world-of-work-2/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DFB28CA790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def extract_article_text(url,df1):\n",
    "    try:\n",
    "        # Send a HEAD request to check the status code\n",
    "        response = requests.head(url)\n",
    "        if response.status_code == 404:\n",
    "            print(f\"Error 404: {url} not found. Skipping.\")\n",
    "            return None, None\n",
    "\n",
    "        # Send a GET request to the URL\n",
    "        response = requests.get(url)\n",
    "        response.raise_for_status()  # Check for errors in the response\n",
    "\n",
    "        # Parse HTML content using BeautifulSoup\n",
    "        soup = BeautifulSoup(response.content, 'html.parser')\n",
    "\n",
    "        # Extract article title and text\n",
    "        title = soup.title.text.strip() if soup.title else 'No Title'\n",
    "        text = ' '.join([p.text.strip() for p in soup.find_all('p')])\n",
    "\n",
    "        return title, text\n",
    "    except Exception as e:\n",
    "        print(f\"Error processing {url}: {e}\")\n",
    "        return None, None\n",
    "\n",
    "def main():\n",
    "    # Read the Excel file\n",
    "    df = pd.read_excel('input.xlsx')\n",
    "    df1=pd.DataFrame(df)\n",
    "   \n",
    "\n",
    "    # Iterate through rows and process each URL\n",
    "    for index, row in df.iterrows():\n",
    "        url = row['URL']\n",
    "        title, text = extract_article_text(url,df1)\n",
    "\n",
    "        if title and text:\n",
    "            # Get the value of 'URL_ID' column to name the output file\n",
    "            url_id = str(row['URL_ID'])\n",
    "            \n",
    "            # Create a text file based on 'URL_ID'\n",
    "            output_filename = f'{url_id}.txt'\n",
    "\n",
    "            # Write the title and text to the text file\n",
    "            with open(output_filename, 'w', encoding='utf-8') as output_file:\n",
    "                output_file.write(f\"Title: {title}\\n\\n\")\n",
    "                output_file.write(f\"Text: {text}\\n\\n\")\n",
    "                output_file.write(\"=\" * 50 + \"\\n\")\n",
    "    df1.to_csv(\"RefinedInputs.csv\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
